# Generated by Django 3.2.5 on 2022-06-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicationstatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.TextField()),
                ('patientid', models.TextField(db_column='patientId')),
            ],
            options={
                'db_table': 'medicationStatement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding', models.TextField()),
                ('value', models.FloatField()),
                ('unit', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('patientidentifier', models.TextField(blank=True, db_column='patientIdentifier', null=True)),
            ],
            options={
                'db_table': 'observation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('name', models.TextField()),
                ('gender', models.TextField()),
                ('birthdate', models.TextField(db_column='birthDate')),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
    ]
